import type { Request, ResponseToolkit, ServerRoute } from "@hapi/hapi";
import { z } from "zod";
import { bearerScope } from "../../../server/plugins/bearer-scope.js";
import { zodResponse } from "../../../server/plugins/zod-response.js";

/** Connect-a-cluster hand-out (#1572): serves URLs and registration token to satellite installers. */

const DEFAULT_REPO_URL = "https://github.com/re-cinq/lore";

export interface InstallInfo {
  available: boolean;
  /** What is missing when `available` is false — the UI renders this. */
  reason: string | null;
  api_url: string | null;
  event_router_url: string | null;
  registration_token: string | null;
  repo_url: string;
}

const InstallInfoResponse = z.object({
  available: z.boolean(),
  reason: z.string().nullable(),
  api_url: z.string().nullable(),
  event_router_url: z.string().nullable(),
  registration_token: z.string().nullable(),
  repo_url: z.string(),
});

interface InstallEnv {
  LORE_API_URL?: string;
  LORE_EVENT_ROUTER_PUBLIC_URL?: string;
  LORE_CLUSTER_AGENT_REGISTRATION_TOKEN?: string;
  LORE_REPO_URL?: string;
}

function missingEnvVars(env: InstallEnv): string[] {
  return [
    env.LORE_CLUSTER_AGENT_REGISTRATION_TOKEN
      ? null
      : "LORE_CLUSTER_AGENT_REGISTRATION_TOKEN (satellite registration is disabled)",
    env.LORE_API_URL ? null : "LORE_API_URL",
    env.LORE_EVENT_ROUTER_PUBLIC_URL ? null : "LORE_EVENT_ROUTER_PUBLIC_URL",
  ].filter((entry): entry is string => entry !== null);
}

function unavailableReason(missing: readonly string[]): string | null {
  return missing.length === 0
    ? null
    : `not configured on the lore-api deployment: ${missing.join(", ")}`;
}

const orNull = (value: string | undefined): string | null => value ?? null;

/** Pure: what this deployment can hand a satellite installer. */
export function buildInstallInfo(env: InstallEnv): InstallInfo {
  const missing = missingEnvVars(env);

  return {
    available: missing.length === 0,
    reason: unavailableReason(missing),
    api_url: orNull(env.LORE_API_URL),
    event_router_url: orNull(env.LORE_EVENT_ROUTER_PUBLIC_URL),
    registration_token: orNull(env.LORE_CLUSTER_AGENT_REGISTRATION_TOKEN),
    repo_url: env.LORE_REPO_URL ?? DEFAULT_REPO_URL,
  };
}

const shellQuote = (value: string): string =>
  `'${value.replace(/'/g, `'\\''`)}'`;

/** Pure: the ready-to-run installer for an `available` deployment. */
export function renderInstallScript(install: InstallInfo): string {
  return `#!/usr/bin/env bash
# Generated by ${install.api_url} — connect this Kubernetes cluster to Lore as a
# satellite (specs/running-stations-in-any-k8s-cluster). Point kubectl at the
# target cluster, then:
#
#   bash install-satellite.sh --name my-cluster --tags node:agent
#
# Also needed in the env: GHCR_USERNAME/GHCR_TOKEN (image pulls) and
# CLAUDE_CODE_OAUTH_TOKEN (bills a subscription) or ANTHROPIC_API_KEY.
# Holding this file means being able to register clusters — treat it as a
# credential; rotating the central registration token revokes it.
set -euo pipefail

export LORE_API_URL=${shellQuote(install.api_url ?? "")}
export EVENT_ROUTER_URL=${shellQuote(install.event_router_url ?? "")}
export LORE_CLUSTER_AGENT_REGISTRATION_TOKEN=${shellQuote(install.registration_token ?? "")}

# Inside a checkout the local installer runs directly; anywhere else the repo
# is cloned shallow into a throwaway dir.
if [ -f "$(dirname "$0")/install-satellite.sh" ]; then
	exec "$(dirname "$0")/install-satellite.sh" "$@"
fi

if [ -f scripts/install-satellite.sh ]; then
	exec scripts/install-satellite.sh "$@"
fi

command -v git >/dev/null 2>&1 || {
	echo "[lore] ERROR: git is required outside a repo checkout" >&2
	exit 1
}
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
echo "[lore] cloning ${install.repo_url} (shallow)"
git clone --quiet --depth 1 ${shellQuote(install.repo_url)} "$tmp/lore"
exec "$tmp/lore/scripts/install-satellite.sh" "$@"
`;
}

export function clusterAgentInstallRoutes(): ServerRoute[] {
  return [
    {
      method: "GET",
      path: "/api/cluster-agents/install-info",
      options: zodResponse(bearerScope("admin"), InstallInfoResponse, {
        name: "ClusterAgentInstallInfo",
        description:
          "What this deployment can hand a satellite installer — URLs and the registration token, or why not",
      }),
      handler: (_request: Request, h: ResponseToolkit) =>
        h.response(buildInstallInfo(process.env)).code(200),
    },
    {
      method: "GET",
      path: "/api/cluster-agents/install.sh",
      options: bearerScope("admin"),
      handler: (_request: Request, h: ResponseToolkit) => {
        const install = buildInstallInfo(process.env);

        if (!install.available) {
          return h
            .response({ error: install.reason ?? "unavailable" })
            .code(404);
        }

        return h
          .response(renderInstallScript(install))
          .type("text/x-shellscript")
          .code(200);
      },
    },
  ];
}
