import { specFilePrompts } from "./feature-request-prompts.js";
import { errorMessage } from "@re-cinq/lore-shared";
import { enforceTrue } from "@re-cinq/lore-shared/lib/enforce.js";
import { Llm } from "@re-cinq/lore-shared";
import { projectFor } from "../../outbound/project-boot.js";
import { fetchRepoContext } from "./repo-context.js";
import type { TaskHandlerInput } from "./task-handler-input.js";
import { writeEpisode } from "@re-cinq/lore-shared";
import { chunks, memoryLifecycle } from "../../outbound/queues.js";
import {
  slugify,
  setStatus,
  insertEvent,
  issueRef,
  linkPrToIssue,
} from "./task-helpers.js";

interface SpecFileRequest {
  path: string;
  prompt: string;
}

/** Generates one spec artifact's content; returns null when the model says the file isn't needed. */
async function generateSpecFileContent(
  file: SpecFileRequest,
  contextStr: string,
  model: string | undefined,
  taskId: string,
): Promise<string | null> {
  const result = await Llm.instance.complete({
    prompt: `${file.prompt}\n\n## Repository Context\n\n${contextStr}`,
    systemPrompt: `Generate the content for ${file.path}. Output ONLY the file content — no explanation, no markdown code fences, no preamble. Start directly with the file content.`,
    model,
    maxTokens: 8192,
    taskId,
  });
  const text = result.text.trim();

  return text === "SKIP" || text.length < 20 ? null : text;
}

/** Translates a PM's plain-language intent into spec.md/data-model.md/tasks.md matching the target repo's conventions, then opens a PR for engineer review. */
/** Reads the repo once: the context every artifact is generated against, and an existing spec to copy the house format from, so generated specs match what the repo already writes. */
async function planSpecGeneration(
  targetRepo: string,
  pmIntent: string,
): Promise<{
  contextStr: string;
  featureSlug: string;
  specFiles: ReturnType<typeof specFilePrompts>;
}> {
  console.log(`[floor] Feature request: fetching context for ${targetRepo}...`);
  const context = await fetchRepoContext(targetRepo);
  const featureSlug = slugify(pmIntent);
  const specFiles = specFilePrompts(
    pmIntent,
    await specFormatExample(targetRepo),
  );

  console.log(
    `[floor] Feature request: generating ${specFiles.length} artifacts for "${featureSlug}"...`,
  );

  return {
    contextStr: JSON.stringify(context, null, 2),
    featureSlug,
    specFiles,
  };
}

/** Labelled `needs-review`, never auto-merged: a spec generated from plain language is a proposal for engineers to refine, not a change to land. */
async function openSpecPr(input: {
  project: Awaited<ReturnType<typeof projectFor>>;
  branchName: string;
  featureSlug: string;
  pmIntent: string;
  committed: string[];
  task: TaskHandlerInput["task"];
  issueNumber: TaskHandlerInput["issueNumber"];
}): Promise<{ url: string; number: number }> {
  const { project, branchName, featureSlug, pmIntent, committed, task } = input;
  const fileList = committed.map((f) => `- \`${f}\``).join("\n");

  return await project.pulls.open(branchName, {
    title: `spec: ${featureSlug}`,
    body: `## Feature Request → Spec\n\n**PM intent:** ${pmIntent}\n\n**Generated artifacts:**\n${fileList}\n\nThis spec was generated from a plain-language feature request. Engineers should review, refine, and merge before implementation.\n\nGenerated by Lore agent task \`${task.id}\`.${issueRef(input.issueNumber, task.id)}`,
    base: await project.repo.defaultBranch(),
    labels: ["spec", "needs-review"],
  });
}

/** Everything that follows the PR existing: the Issue link, the task status and its event, and the episode. The episode is fire-and-forget — a memory write must never fail a task whose PR is already open. */
async function recordSpecPr(input: {
  targetRepo: string;
  branchName: string;
  task: TaskHandlerInput["task"];
  issueNumber: TaskHandlerInput["issueNumber"];
  pmIntent: string;
  committed: string[];
  pr: { url: string; number: number };
}): Promise<void> {
  const { targetRepo, branchName, task, issueNumber, pmIntent, committed, pr } =
    input;

  await linkPrToIssue(targetRepo, issueNumber, pr.url);

  await setStatus(task.id, "pr-created", {
    pr_url: pr.url,
    pr_number: pr.number,
    target_branch: branchName,
  });
  await insertEvent(task.id, "running", "pr-created", { pr_url: pr.url });

  writeEpisode(
    { memory: memoryLifecycle() },
    {
      content: `Feature request spec generated for ${targetRepo}\nPM intent: ${pmIntent.substring(0, 300)}\nArtifacts: ${committed.join(", ")}\nPR: ${pr.url}`,
      source: "ci",
      ref: `${targetRepo}/${task.id}`,
    },
  ).catch(() => {});
}

/** Opens the PR, then records it against the task. Kept together and in this order: a spec PR with no task row is invisible to every later step, while a row pointing at a PR that failed to open would strand the task. */
async function publishSpecPr(
  where: {
    project: Awaited<ReturnType<typeof projectFor>>;
    targetRepo: string;
    branchName: string;
    featureSlug: string;
  },
  what: {
    task: TaskHandlerInput["task"];
    issueNumber: number | null;
    pmIntent: string;
    committed: string[];
  },
): Promise<{ url: string }> {
  const pr = await openSpecPr({
    project: where.project,
    branchName: where.branchName,
    featureSlug: where.featureSlug,
    ...what,
  });

  await recordSpecPr({
    targetRepo: where.targetRepo,
    branchName: where.branchName,
    ...what,
    pr,
  });

  return pr;
}

/** Plans the artifacts, creates the branch, and commits what the model wrote. An empty branch is a failure rather than an empty feature — the PR would ask a human to review nothing. */
async function buildSpecBranch(
  where: {
    project: Awaited<ReturnType<typeof projectFor>>;
    targetRepo: string;
    branchName: string;
    pmIntent: string;
  },
  run: { model: string | undefined; taskId: string },
): Promise<{ featureSlug: string; committed: string[] }> {
  const { project, targetRepo, branchName, pmIntent } = where;
  const { contextStr, featureSlug, specFiles } = await planSpecGeneration(
    targetRepo,
    pmIntent,
  );

  await project.repo.createBranch(branchName);

  const committed = await commitGeneratedSpecs(specFiles, {
    project,
    branchName,
    contextStr,
    model: run.model,
    taskId: run.taskId,
  });

  enforceTrue(
    committed.length !== 0,
    Error,
    "Failed to generate any spec artifacts",
  );

  return { featureSlug, committed };
}

export async function handleFeatureRequest({
  task,
  targetRepo,
  branchName,
  model,
  issueNumber,
}: TaskHandlerInput): Promise<void> {
  const project = await projectFor(targetRepo);
  const pmIntent = task.description;
  const { featureSlug, committed } = await buildSpecBranch(
    { project, targetRepo, branchName, pmIntent },
    { model, taskId: task.id },
  );

  const pr = await publishSpecPr(
    { project, targetRepo, branchName, featureSlug },
    { task, issueNumber, pmIntent, committed },
  );

  console.log(
    `[floor] Task ${task.id} → PR ${pr.url} (${committed.length} spec artifacts)`,
  );
}

/** An existing spec, if the repo has one, so the generated files match the house format rather than a generic template. */
async function specFormatExample(targetRepo: string): Promise<string> {
  try {
    // Through the chunks port, not a hand-rolled second copy of its schema-resolution SELECT — that duplication used to silently swallow errors inside a catch, costing every feature-request its format example.
    const specs = await chunks().specChunks(targetRepo);
    const firstSpec = specs.at(0);

    return firstSpec
      ? `\n\n## Existing Spec Example (match this format)\n\n${firstSpec.content.substring(0, 3000)}`
      : "";
  } catch {
    /* no specs in DB yet, that's fine */
    return "";
  }
}

/** Generate each artifact and commit it; a file the model declines to write is skipped, and one failure does not cost the others. */
/** Everything a spec artifact needs to reach the branch: where it goes, and what the model is told. */
interface SpecCommitContext {
  project: Awaited<ReturnType<typeof projectFor>>;
  branchName: string;
  contextStr: string;
  model: string | undefined;
  taskId: string;
}

/** Generates one artifact and commits it. Returns false when the model declines to write the file — an optional artifact (a feature with no data-model change) is a real answer, not a failure. */
async function commitOneSpec(
  file: { path: string; prompt: string },
  ctx: SpecCommitContext,
): Promise<boolean> {
  const text = await generateSpecFileContent(
    file,
    ctx.contextStr,
    ctx.model,
    ctx.taskId,
  );

  if (text === null) {
    console.log(`[floor] Feature request: skipping ${file.path} (not needed)`);

    return false;
  }
  const { repo } = ctx.project;

  await repo.commitFile(
    ctx.branchName,
    file.path,
    text,
    `lore: add ${file.path}`,
  );
  console.log(
    `[floor] Feature request: committed ${file.path} (${text.length} chars)`,
  );

  return true;
}

/** Generate each artifact and commit it; one failure does not cost the others — a spec.md is worth opening a PR for even when the data-model generation failed. */
async function commitGeneratedSpecs(
  files: { path: string; prompt: string }[],
  ctx: SpecCommitContext,
): Promise<string[]> {
  const committed: string[] = [];

  for (const file of files) {
    try {
      if (await commitOneSpec(file, ctx)) {
        committed.push(file.path);
      }
    } catch (err) {
      console.error(
        `[floor] Feature request: failed ${file.path}: ${errorMessage(err)}`,
      );
    }
  }

  return committed;
}

/** The three artifacts a feature request becomes, and what each one asks for. */
