import { errorMessage } from "@re-cinq/lore-shared";
import { enforceTrue } from "@re-cinq/lore-shared/lib/enforce.js";
import { Llm } from "@re-cinq/lore-shared";
import { projectFor } from "../../composition/project-boot.js";
import { fetchRepoContext } from "./repo-context.js";
import type { TaskHandlerInput } from "./task-handler-input.js";
import { writeEpisode } from "@re-cinq/lore-shared";
import { chunks, memoryLifecycle } from "../../kernel/queues.js";
import {
  slugify,
  setStatus,
  insertEvent,
  issueRef,
  linkPrToIssue,
} from "./task-helpers.js";

interface SpecFileRequest {
  path: string;
  prompt: string;
}

/** Generates one spec artifact's content; returns null when the model says the file isn't needed. */
async function generateSpecFileContent(
  file: SpecFileRequest,
  contextStr: string,
  model: string | undefined,
  taskId: string,
): Promise<string | null> {
  const result = await Llm.instance.complete({
    prompt: `${file.prompt}\n\n## Repository Context\n\n${contextStr}`,
    systemPrompt: `Generate the content for ${file.path}. Output ONLY the file content — no explanation, no markdown code fences, no preamble. Start directly with the file content.`,
    model,
    maxTokens: 8192,
    taskId,
  });
  const text = result.text.trim();

  return text === "SKIP" || text.length < 20 ? null : text;
}

/** Translates a PM's plain-language intent into spec.md/data-model.md/tasks.md matching the target repo's conventions, then opens a PR for engineer review. */
export async function handleFeatureRequest({
  task,
  targetRepo,
  branchName,
  model,
  issueNumber,
}: TaskHandlerInput): Promise<void> {
  const project = await projectFor(targetRepo);

  console.log(`[floor] Feature request: fetching context for ${targetRepo}...`);
  const context = await fetchRepoContext(targetRepo);
  const contextStr = JSON.stringify(context, null, 2);
  const pmIntent = task.description;
  const featureSlug = slugify(pmIntent);
  const SPEC_FILES = specFilePrompts(
    pmIntent,
    await specFormatExample(targetRepo),
  );

  console.log(
    `[floor] Feature request: generating ${SPEC_FILES.length} artifacts for "${featureSlug}"...`,
  );
  await project.repo.createBranch(branchName);
  const committed = await commitGeneratedSpecs(SPEC_FILES, {
    project,
    branchName,
    contextStr,
    model,
    taskId: task.id,
  });

  enforceTrue(
    committed.length !== 0,
    Error,
    "Failed to generate any spec artifacts",
  );
  const fileList = committed.map((f) => `- \`${f}\``).join("\n");
  const pr = await project.pulls.open(branchName, {
    title: `spec: ${featureSlug}`,
    body: `## Feature Request → Spec\n\n**PM intent:** ${pmIntent}\n\n**Generated artifacts:**\n${fileList}\n\nThis spec was generated from a plain-language feature request. Engineers should review, refine, and merge before implementation.\n\nGenerated by Lore agent task \`${task.id}\`.${issueRef(issueNumber, task.id)}`,
    base: await project.repo.defaultBranch(),
    labels: ["spec", "needs-review"],
  });

  await linkPrToIssue(targetRepo, issueNumber, pr.url);

  await setStatus(task.id, "pr-created", {
    pr_url: pr.url,
    pr_number: pr.number,
    target_branch: branchName,
  });
  await insertEvent(task.id, "running", "pr-created", { pr_url: pr.url });

  writeEpisode(
    { memory: memoryLifecycle() },
    {
      content: `Feature request spec generated for ${targetRepo}\nPM intent: ${pmIntent.substring(0, 300)}\nArtifacts: ${committed.join(", ")}\nPR: ${pr.url}`,
      source: "ci",
      ref: `${targetRepo}/${task.id}`,
    },
  ).catch(() => {});

  console.log(
    `[floor] Task ${task.id} → PR ${pr.url} (${committed.length} spec artifacts)`,
  );
}

/** An existing spec, if the repo has one, so the generated files match the house format rather than a generic template. */
async function specFormatExample(targetRepo: string): Promise<string> {
  try {
    // Through the chunks port, not a hand-rolled second copy of its schema-resolution SELECT — that duplication used to silently swallow errors inside a catch, costing every feature-request its format example.
    const specs = await chunks().specChunks(targetRepo);

    return specs.length > 0
      ? `\n\n## Existing Spec Example (match this format)\n\n${specs[0].content.substring(0, 3000)}`
      : "";
  } catch {
    /* no specs in DB yet, that's fine */
    return "";
  }
}

/** Generate each artifact and commit it; a file the model declines to write is skipped, and one failure does not cost the others. */
async function commitGeneratedSpecs(
  files: { path: string; prompt: string }[],
  ctx: {
    project: Awaited<ReturnType<typeof projectFor>>;
    branchName: string;
    contextStr: string;
    model: string | undefined;
    taskId: string;
  },
): Promise<string[]> {
  const committed: string[] = [];

  for (const file of files) {
    try {
      const text = await generateSpecFileContent(
        file,
        ctx.contextStr,
        ctx.model,
        ctx.taskId,
      );

      if (text === null) {
        console.log(
          `[floor] Feature request: skipping ${file.path} (not needed)`,
        );
        continue;
      }
      await ctx.project.repo.commitFile(
        ctx.branchName,
        file.path,
        text,
        `lore: add ${file.path}`,
      );
      committed.push(file.path);
      console.log(
        `[floor] Feature request: committed ${file.path} (${text.length} chars)`,
      );
    } catch (err) {
      console.error(
        `[floor] Feature request: failed ${file.path}: ${errorMessage(err)}`,
      );
    }
  }

  return committed;
}

/** The three artifacts a feature request becomes, and what each one asks for. */
function specFilePrompts(
  pmIntent: string,
  existingSpecExample: string,
): { path: string; prompt: string }[] {
  const featureSlug = slugify(pmIntent);

  return [
    {
      path: `specs/${featureSlug}/spec.md`,
      prompt: `Write a feature specification for the following product request.

The PM said: "${pmIntent}"

Write a proper engineering spec with these sections:
- Problem Statement (what problem does this solve for users?)
- Vision (what does the end state look like?)
- User Scenarios & Acceptance Criteria (concrete flows with testable criteria)
- Functional Requirements (numbered, testable)
- Non-Functional Requirements (performance, security if relevant)
- Out of Scope (what this does NOT include)
- Key Entities (data model implications)
- Success Criteria (measurable outcomes)
- Assumptions

Match the conventions and style of this repository. Be specific to the actual tech stack and architecture described in CLAUDE.md.${existingSpecExample}`,
    },
    {
      path: `specs/${featureSlug}/data-model.md`,
      prompt: `Based on this feature request, define the data model changes needed.

The PM said: "${pmIntent}"

If the feature requires new tables, fields, or relationships, document them with:
- Table name, fields, types, constraints
- Relationships to existing entities
- Migration notes

If no data model changes are needed, respond with just "SKIP".

Look at the existing schema in CLAUDE.md and any existing data models for conventions.`,
    },
    {
      path: `specs/${featureSlug}/tasks.md`,
      prompt: `Create a task breakdown for implementing this feature.

The PM said: "${pmIntent}"

Generate tasks in checklist format:
- [ ] T001 [P] Description with file path
- [ ] T002 Description with file path

Organize into phases:
- Phase 1: Setup (project scaffolding, dependencies)
- Phase 2: Core (main implementation)
- Phase 3: Integration (wiring, testing, polish)

Mark parallelizable tasks with [P]. Include file paths based on the actual project structure visible in the repo context. Each task must be specific enough for an engineer (or AI agent) to execute without additional context.`,
    },
  ];
}
