apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: lore-floor
data:
  task-types.yaml: |
    {{- .Values.taskTypesConfig | default "" | nindent 4 }}
