/**
 * LoreTask watcher job.
 *
 * Polls LoreTask custom resources for completed (Succeeded / Failed) CRs.
 * On success, creates a PR from the branch the ephemeral Job pushed.
 * On failure, updates the pipeline task with the error.
 * Cleans up old CRs after 1 hour.
 */

import { KubeConfig, CustomObjectsApi, CoreV1Api } from "@kubernetes/client-node";
import { platform } from "../platform.js";
import { query } from "../db.js";

// ── Helpers ─────────────────────────────────────────────────────────

async function getIssueNumber(taskId: string): Promise<{ issue_number: number | null; target_repo: string }> {
  const rows = await query<{ issue_number: number | null; target_repo: string }>(
    `SELECT issue_number, target_repo FROM pipeline.tasks WHERE id = $1`,
    [taskId],
  );
  return rows[0] || { issue_number: null, target_repo: "" };
}

async function linkPrToIssue(repo: string, issueNumber: number | null, prUrl: string): Promise<void> {
  if (!issueNumber) return;
  try {
    await platform().commentOnIssue(repo, issueNumber, `PR created: ${prUrl}`);
    await platform().closeIssue(repo, issueNumber, "completed");
  } catch { /* best effort */ }
}

async function commentFailureOnIssue(repo: string, issueNumber: number | null, reason: string): Promise<void> {
  if (!issueNumber) return;
  try {
    await platform().commentOnIssue(repo, issueNumber, `Task failed: \`${reason}\``);
    await platform().addIssueLabel(repo, issueNumber, "lore-failed");
  } catch { /* best effort */ }
}

const GROUP = "lore.re-cinq.com";
const VERSION = "v1alpha1";
const PLURAL = "loretasks";

export async function watchLoreTasks(): Promise<void> {
  const kc = new KubeConfig();
  kc.loadFromCluster();
  const k8sApi = kc.makeApiClient(CustomObjectsApi);
  const namespace = process.env.NAMESPACE || "lore-agent";

  const result = await k8sApi.listNamespacedCustomObject({
    group: GROUP,
    version: VERSION,
    namespace,
    plural: PLURAL,
  });
  const items = (result as any).items || [];

  for (const lt of items) {
    const phase = lt.status?.phase;
    const taskId = lt.spec?.taskId;
    if (!taskId) continue;

    if (phase === "Succeeded" && !lt.status?.prUrl) {
      // Create PR from the pushed branch
      try {
        const { issue_number, target_repo } = await getIssueNumber(taskId);
        const issueRef = issue_number ? `\n\nRefs #${issue_number}` : "";

        const pr = await platform().createPR(
          lt.spec.targetRepo,
          lt.spec.branch,
          `lore: ${lt.spec.taskType} — ${lt.spec.branch.split("/").pop()}`,
          `## ${lt.spec.taskType}\n\n${lt.spec.description}\n\n**Execution mode:** Claude Code (ephemeral Job)\n**Changed files:** ${lt.status.changedFiles || "unknown"}\n\nGenerated by Lore agent task \`${taskId}\`.${issueRef}`,
        );

        // Update pipeline.tasks
        await query(
          `UPDATE pipeline.tasks SET status = 'pr-created', pr_url = $1, pr_number = $2, target_branch = $3, updated_at = now() WHERE id = $4`,
          [pr.url, pr.number, lt.spec.branch, taskId],
        );
        await query(
          `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, 'running', 'pr-created', $2)`,
          [taskId, JSON.stringify({ pr_url: pr.url })],
        );

        // Link PR to GitHub Issue and close it
        await linkPrToIssue(target_repo, issue_number, pr.url);

        // Update LoreTask status with PR URL
        const current = await k8sApi.getNamespacedCustomObjectStatus({
          group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
        }) as any;
        await k8sApi.replaceNamespacedCustomObjectStatus({
          group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
          body: { ...current, status: { ...current.status, prUrl: pr.url, prNumber: pr.number } },
        });

        console.log(`[loretask-watcher] Task ${taskId} → PR ${pr.url}`);
      } catch (err: any) {
        console.error(`[loretask-watcher] Failed to create PR for ${taskId}: ${err.message}`);
      }
    }

    if (phase === "Failed" && lt.status?.failureReason) {
      // Update pipeline.tasks with failure
      const rows = await query<{ status: string; issue_number: number | null; target_repo: string }>(
        `SELECT status, issue_number, target_repo FROM pipeline.tasks WHERE id = $1`, [taskId],
      );
      if (rows[0]?.status === "running") {
        await query(
          `UPDATE pipeline.tasks SET status = 'failed', failure_reason = $1, updated_at = now() WHERE id = $2`,
          [lt.status.failureReason, taskId],
        );
        await query(
          `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, 'running', 'failed', $2)`,
          [taskId, JSON.stringify({ error: lt.status.failureReason })],
        );
        await commentFailureOnIssue(rows[0].target_repo, rows[0].issue_number, lt.status.failureReason);
        console.log(`[loretask-watcher] Task ${taskId} failed: ${lt.status.failureReason}`);
      }
    }

    // Clean up old completed LoreTasks (> 1 hour old with PR or failed)
    if ((phase === "Succeeded" && lt.status?.prUrl) || (phase === "Failed")) {
      const completedAt = lt.status?.completedAt ? new Date(lt.status.completedAt) : null;
      if (completedAt && Date.now() - completedAt.getTime() > 60 * 60 * 1000) {
        const taskIdShort = taskId.substring(0, 8);
        try {
          await k8sApi.deleteNamespacedCustomObject({
            group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
          });
          console.log(`[loretask-watcher] Cleaned up LoreTask ${lt.metadata.name}`);
        } catch { /* best effort */ }
        // Clean up orphaned token secret
        try {
          const coreApi = kc.makeApiClient(CoreV1Api);
          await coreApi.deleteNamespacedSecret({ name: `loretask-github-token-${taskIdShort}`, namespace });
        } catch { /* already gone or never created */ }
      }
    }
  }
}

/**
 * Job wrapper for the scheduler. Returns a summary string.
 */
export async function loretaskWatcherJob(): Promise<string> {
  await watchLoreTasks();
  return "LoreTask watcher completed";
}
