#!/usr/bin/env bash
# Fail if the seeded ai-agents-helm catalog has drifted from scripts/task-types.yaml.
# The catalog (infra/terraform/modules/gke-mcp/lore-platform/charts/ai-agents-helm/files/catalog-seed.yaml)
# is generated by apps/floor's gen-catalog from the task-type recipes. Regenerate:
#
#   npm run build -w @re-cinq/lore-floor && npm run gen:catalog -w @re-cinq/lore-floor
set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo"

npm run build -w @re-cinq/lore-floor >/dev/null
npm run gen:catalog -w @re-cinq/lore-floor >/dev/null

catalog="infra/terraform/modules/gke-mcp/lore-platform/charts/ai-agents-helm/files/catalog-seed.yaml"
if git diff --quiet -- "$catalog"; then
	echo "ai-agents catalog is in sync with scripts/task-types.yaml."
else
	echo >&2
	echo "ERROR: the ai-agents catalog is out of sync with scripts/task-types.yaml." >&2
	echo "Regenerate: npm run build -w @re-cinq/lore-floor && npm run gen:catalog -w @re-cinq/lore-floor" >&2
	git --no-pager diff -- "$catalog" >&2
	exit 1
fi
