/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/repo-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repo-status */
    get: operations["get_api_repo-status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos */
    get: operations["get_api_repos"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo} */
    get: operations["get_api_repos_owner_repo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pr-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/pr-status */
    get: operations["get_api_pr-status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/context": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/context */
    get: operations["get_api_context"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/graph": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/graph */
    get: operations["get_api_graph"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/task/{id} */
    get: operations["get_api_task_id"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/tasks */
    get: operations["get_api_tasks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{id}/timeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/tasks/{id}/timeline */
    get: operations["get_api_tasks_id_timeline"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/tasks/{id}/runs */
    get: operations["get_api_tasks_id_runs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/by-pr/{owner}/{repo}/{number}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/tasks/by-pr/{owner}/{repo}/{number} */
    get: operations["get_api_tasks_by-pr_owner_repo_number"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/task-logs */
    get: operations["get_api_task-logs"];
    put?: never;
    /** POST /api/task-logs */
    post: operations["post_api_task-logs"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/job-run-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/job-run-logs */
    get: operations["get_api_job-run-logs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/task */
    post: operations["post_api_task"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task-groups/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/task-groups/{id} */
    get: operations["get_api_task-groups_id"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/spec-tasks/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/spec-tasks/sync */
    post: operations["post_api_spec-tasks_sync"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/spec-tasks/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/spec-tasks/ready */
    get: operations["get_api_spec-tasks_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/spec-tasks/claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/spec-tasks/claim */
    post: operations["post_api_spec-tasks_claim"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/spec-tasks/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/spec-tasks/complete */
    post: operations["post_api_spec-tasks_complete"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/memory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/memory */
    post: operations["post_api_memory"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/episode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/episode */
    post: operations["post_api_episode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/session-summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/session-summary */
    post: operations["post_api_session-summary"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ingest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/ingest */
    post: operations["post_api_ingest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/ingest-graph": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/ingest-graph */
    post: operations["post_api_repos_owner_repo_ingest-graph"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/events/{id}/payload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/events/{id}/payload */
    get: operations["get_api_repos_owner_repo_events_id_payload"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/embed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/embed */
    post: operations["post_api_embed"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/onboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/onboard */
    post: operations["post_api_onboard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/webhook/slack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * POST /api/webhook/slack
     * @description Request body is verified and parsed by the handler (HMAC/form-encoded), not JSON.
     */
    post: operations["post_api_webhook_slack"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/webhook/incident": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * POST /api/webhook/incident
     * @description Request body is verified and parsed by the handler (HMAC/form-encoded), not JSON.
     */
    post: operations["post_api_webhook_incident"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/webhook": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/webhook */
    get: operations["get_api_repos_owner_repo_webhook"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/webhook/ensure": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/webhook/ensure */
    post: operations["post_api_repos_owner_repo_webhook_ensure"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/webhook/secret": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/webhook/secret */
    get: operations["get_api_repos_owner_repo_webhook_secret"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/tokens */
    get: operations["get_api_tokens"];
    put?: never;
    /** POST /api/tokens */
    post: operations["post_api_tokens"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/settings/dark-factory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/settings/dark-factory */
    get: operations["get_api_repos_owner_repo_settings_dark-factory"];
    /** PUT /api/repos/{owner}/{repo}/settings/dark-factory */
    put: operations["put_api_repos_owner_repo_settings_dark-factory"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/agent-definitions/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GET /api/repos/{owner}/{repo}/agent-definitions/{name}
     * @description A trailing path parameter is optional; omit it for the collection form.
     */
    get: operations["get_api_repos_owner_repo_agent-definitions_name"];
    /** PUT /api/repos/{owner}/{repo}/agent-definitions/{name} */
    put: operations["put_api_repos_owner_repo_agent-definitions_name"];
    post?: never;
    /** DELETE /api/repos/{owner}/{repo}/agent-definitions/{name} */
    delete: operations["delete_api_repos_owner_repo_agent-definitions_name"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/agent-definitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/agent-definitions */
    post: operations["post_api_repos_owner_repo_agent-definitions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/usage */
    get: operations["get_api_usage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/analytics */
    get: operations["get_api_analytics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agent-stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/agent-stats */
    get: operations["get_api_agent-stats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/impact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/impact */
    post: operations["post_api_repos_owner_repo_impact"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/impact/base": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/impact/base */
    get: operations["get_api_repos_owner_repo_impact_base"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/trace/{kind}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/trace/{kind} */
    get: operations["get_api_repos_owner_repo_trace_kind"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/chunks/{kind}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/chunks/{kind} */
    get: operations["get_api_repos_owner_repo_chunks_kind"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/onboarded": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/onboarded */
    get: operations["get_api_repos_owner_repo_onboarded"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/issues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/issues */
    get: operations["get_api_repos_owner_repo_issues"];
    put?: never;
    /** POST /api/repos/{owner}/{repo}/issues */
    post: operations["post_api_repos_owner_repo_issues"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/labels */
    get: operations["get_api_repos_owner_repo_labels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/branches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/branches */
    post: operations["post_api_repos_owner_repo_branches"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/commit */
    post: operations["post_api_repos_owner_repo_commit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/pulls": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/pulls */
    post: operations["post_api_repos_owner_repo_pulls"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/ci-conclusion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/ci-conclusion */
    get: operations["get_api_repos_owner_repo_ci-conclusion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/tasks/drift": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/tasks/drift */
    get: operations["get_api_repos_owner_repo_tasks_drift"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/tasks/open-like": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/tasks/open-like */
    get: operations["get_api_repos_owner_repo_tasks_open-like"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/tasks */
    post: operations["post_api_repos_owner_repo_tasks"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trace/adrs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/trace/adrs */
    get: operations["get_api_trace_adrs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trace/specs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/trace/specs */
    get: operations["get_api_trace_specs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/openapi.json */
    get: operations["get_api_openapi.json"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/docs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/docs */
    get: operations["get_api_docs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/features */
    get: operations["get_api_repos_owner_repo_features"];
    put?: never;
    /** POST /api/repos/{owner}/{repo}/features */
    post: operations["post_api_repos_owner_repo_features"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/features/{id} */
    get: operations["get_api_repos_owner_repo_features_id"];
    put?: never;
    post?: never;
    /** DELETE /api/repos/{owner}/{repo}/features/{id} */
    delete: operations["delete_api_repos_owner_repo_features_id"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features/{id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/features/{id}/status */
    get: operations["get_api_repos_owner_repo_features_id_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features/{id}/decomposition": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/repos/{owner}/{repo}/features/{id}/decomposition */
    get: operations["get_api_repos_owner_repo_features_id_decomposition"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features/{id}/iterations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/features/{id}/iterations */
    post: operations["post_api_repos_owner_repo_features_id_iterations"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features/{id}/iterations/{n}/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/features/{id}/iterations/{n}/result */
    post: operations["post_api_repos_owner_repo_features_id_iterations_n_result"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features/{id}/finalize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/features/{id}/finalize */
    post: operations["post_api_repos_owner_repo_features_id_finalize"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repos/{owner}/{repo}/features/{id}/split": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/repos/{owner}/{repo}/features/{id}/split */
    post: operations["post_api_repos_owner_repo_features_id_split"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: string;
    };
    FeatureList: {
      features: {
        id: string;
        repo: string;
        title: string;
        slug: string;
        path: string;
        original_prompt: string;
        /** @enum {string} */
        status:
          | "draft"
          | "planning"
          | "awaiting-input"
          | "spec-ready"
          | "pr-open"
          | "implemented";
        current_iteration: number;
        draft_spec_md: string | null;
        parent_feature_id: string | null;
        spec_path: string | null;
        spec_pr_url: string | null;
        spec_pr_number: number | null;
        issue_number: number | null;
        issue_url: string | null;
        created_by: string;
        created_at: string;
        updated_at: string;
      }[];
    };
    FeatureCreated: {
      id: string;
      task_id: string;
    };
    FeatureWithIterations: {
      id: string;
      repo: string;
      title: string;
      slug: string;
      path: string;
      original_prompt: string;
      /** @enum {string} */
      status:
        | "draft"
        | "planning"
        | "awaiting-input"
        | "spec-ready"
        | "pr-open"
        | "implemented";
      current_iteration: number;
      draft_spec_md: string | null;
      parent_feature_id: string | null;
      spec_path: string | null;
      spec_pr_url: string | null;
      spec_pr_number: number | null;
      issue_number: number | null;
      issue_url: string | null;
      created_by: string;
      created_at: string;
      updated_at: string;
      iterations: {
        id: string;
        feature_id: string;
        iteration: number;
        task_id: string | null;
        /** @enum {string} */
        status: "running" | "ready" | "failed";
        user_answers: {
          sections?: {
            [key: string]: {
              comment?: string;
              /** @enum {string} */
              direction?: "keep" | "refine" | "redirect";
            };
          };
          questions?: {
            [key: string]: string;
          };
          free_form?: string;
        } | null;
        gap_result: {
          sections?: {
            title: string;
            content?: string;
            mockups?: {
              title?: string;
              /** @enum {string} */
              format?: "svg" | "mermaid" | "html";
              markup: string;
              section?: string;
              height?: number;
            }[];
            questions?: {
              id: string;
              question: string;
              why?: string;
              /** @enum {string} */
              kind?: "text" | "choice";
              options?: string[];
            }[];
          }[];
          mockup_stylesheet?: string;
          architecture?: {
            summary: string;
            components: {
              name: string;
              responsibility: string;
              touchpoints: string[];
            }[];
          };
          user_flows?: {
            name: string;
            steps: string[];
          }[];
          mockups?: {
            title?: string;
            /** @enum {string} */
            format?: "svg" | "mermaid" | "html";
            markup: string;
            section?: string;
            height?: number;
          }[];
          questions?: {
            id: string;
            question: string;
            why?: string;
            /** @enum {string} */
            kind?: "text" | "choice";
            options?: string[];
          }[];
          split_suggestion?: {
            rationale: string;
            proposed_features: {
              title: string;
              scope: string;
            }[];
          };
          draft_spec_markdown?: string;
        } | null;
        parent_iteration: number | null;
        created_at: string;
        updated_at: string;
      }[];
    };
    FeaturePoll: {
      feature: {
        id: string;
        repo: string;
        title: string;
        slug: string;
        path: string;
        original_prompt: string;
        /** @enum {string} */
        status:
          | "draft"
          | "planning"
          | "awaiting-input"
          | "spec-ready"
          | "pr-open"
          | "implemented";
        current_iteration: number;
        draft_spec_md: string | null;
        parent_feature_id: string | null;
        spec_path: string | null;
        spec_pr_url: string | null;
        spec_pr_number: number | null;
        issue_number: number | null;
        issue_url: string | null;
        created_by: string;
        created_at: string;
        updated_at: string;
      };
      latest_iteration: {
        id: string;
        feature_id: string;
        iteration: number;
        task_id: string | null;
        /** @enum {string} */
        status: "running" | "ready" | "failed";
        user_answers: {
          sections?: {
            [key: string]: {
              comment?: string;
              /** @enum {string} */
              direction?: "keep" | "refine" | "redirect";
            };
          };
          questions?: {
            [key: string]: string;
          };
          free_form?: string;
        } | null;
        gap_result: {
          sections?: {
            title: string;
            content?: string;
            mockups?: {
              title?: string;
              /** @enum {string} */
              format?: "svg" | "mermaid" | "html";
              markup: string;
              section?: string;
              height?: number;
            }[];
            questions?: {
              id: string;
              question: string;
              why?: string;
              /** @enum {string} */
              kind?: "text" | "choice";
              options?: string[];
            }[];
          }[];
          mockup_stylesheet?: string;
          architecture?: {
            summary: string;
            components: {
              name: string;
              responsibility: string;
              touchpoints: string[];
            }[];
          };
          user_flows?: {
            name: string;
            steps: string[];
          }[];
          mockups?: {
            title?: string;
            /** @enum {string} */
            format?: "svg" | "mermaid" | "html";
            markup: string;
            section?: string;
            height?: number;
          }[];
          questions?: {
            id: string;
            question: string;
            why?: string;
            /** @enum {string} */
            kind?: "text" | "choice";
            options?: string[];
          }[];
          split_suggestion?: {
            rationale: string;
            proposed_features: {
              title: string;
              scope: string;
            }[];
          };
          draft_spec_markdown?: string;
        } | null;
        parent_iteration: number | null;
        created_at: string;
        updated_at: string;
      } | null;
      last_ready_iteration: {
        id: string;
        feature_id: string;
        iteration: number;
        task_id: string | null;
        /** @enum {string} */
        status: "running" | "ready" | "failed";
        user_answers: {
          sections?: {
            [key: string]: {
              comment?: string;
              /** @enum {string} */
              direction?: "keep" | "refine" | "redirect";
            };
          };
          questions?: {
            [key: string]: string;
          };
          free_form?: string;
        } | null;
        gap_result: {
          sections?: {
            title: string;
            content?: string;
            mockups?: {
              title?: string;
              /** @enum {string} */
              format?: "svg" | "mermaid" | "html";
              markup: string;
              section?: string;
              height?: number;
            }[];
            questions?: {
              id: string;
              question: string;
              why?: string;
              /** @enum {string} */
              kind?: "text" | "choice";
              options?: string[];
            }[];
          }[];
          mockup_stylesheet?: string;
          architecture?: {
            summary: string;
            components: {
              name: string;
              responsibility: string;
              touchpoints: string[];
            }[];
          };
          user_flows?: {
            name: string;
            steps: string[];
          }[];
          mockups?: {
            title?: string;
            /** @enum {string} */
            format?: "svg" | "mermaid" | "html";
            markup: string;
            section?: string;
            height?: number;
          }[];
          questions?: {
            id: string;
            question: string;
            why?: string;
            /** @enum {string} */
            kind?: "text" | "choice";
            options?: string[];
          }[];
          split_suggestion?: {
            rationale: string;
            proposed_features: {
              title: string;
              scope: string;
            }[];
          };
          draft_spec_markdown?: string;
        } | null;
        parent_iteration: number | null;
        created_at: string;
        updated_at: string;
      } | null;
      assembly_line_id: string | null;
    };
    FeatureDecomposition: {
      tasks: {
        description: string;
        status: string;
        context_bundle: {
          [key: string]: unknown;
        } | null;
      }[];
    };
    Ok: {
      /** @constant */
      ok: true;
    };
    RoundStarted: {
      iteration: number;
      task_id?: string | null;
      assembly_line_id?: string;
    };
    FinalizeStarted: {
      task_id?: string;
      assembly_line_id?: string;
    };
    Feature: {
      id: string;
      repo: string;
      title: string;
      slug: string;
      path: string;
      original_prompt: string;
      /** @enum {string} */
      status:
        | "draft"
        | "planning"
        | "awaiting-input"
        | "spec-ready"
        | "pr-open"
        | "implemented";
      current_iteration: number;
      draft_spec_md: string | null;
      parent_feature_id: string | null;
      spec_path: string | null;
      spec_pr_url: string | null;
      spec_pr_number: number | null;
      issue_number: number | null;
      issue_url: string | null;
      created_by: string;
      created_at: string;
      updated_at: string;
    };
  };
  responses: {
    /** @description Malformed or invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description No such resource */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not allowed in the resource's current state */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Missing bearer token */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Token lacks the required scope */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Request body exceeds the size cap */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Rate limit exceeded (Retry-After: 60) */
    RateLimited: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Database or a dependency is unavailable */
    ServiceUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "get_api_repo-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_pr-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_context: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_graph: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_task_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_tasks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_tasks_id_timeline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_tasks_id_runs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_tasks_by-pr_owner_repo_number": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        number: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_task-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "post_api_task-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          task_id: string;
          repo: string;
          logs: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_job-run-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_task: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          action?: string;
          task_id?: string;
          status?: string;
          priority?: string;
          pr_url?: string;
          error?: string;
          description?: string;
          task_type?: string;
          target_repo?: string;
          group_id?: string;
          context?: unknown;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_task-groups_id": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "post_api_spec-tasks_sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          repo: string;
          spec_slug: string;
          tasks_markdown: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_spec-tasks_ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "post_api_spec-tasks_claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          task_id: string;
          agent_id: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "post_api_spec-tasks_complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          task_id: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_memory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | {
              /** @constant */
              action: "write";
              key: string;
              value: string;
              agent_id?: string;
              ttl?: number;
              repo?: string;
              /** @default false */
              extract_facts?: boolean;
            }
          | {
              /** @constant */
              action: "read";
              key: string;
              agent_id?: string;
              version?: string | number;
            }
          | {
              /** @constant */
              action: "search";
              query: string;
              agent_id?: string;
              pool_name?: string;
              limit?: number;
              /** @default false */
              include_invalidated?: boolean;
              /** @default false */
              graph_augment?: boolean;
            }
          | {
              /** @constant */
              action: "delete";
              key: string;
              agent_id?: string;
            }
          | {
              /** @constant */
              action: "list";
              agent_id?: string;
              /** @default 50 */
              limit?: number;
              /** @default 0 */
              offset?: number;
            };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_episode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          content: string;
          source?: string;
          ref?: string;
          agent_id?: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "post_api_session-summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          session_log:
            | string
            | ({
                summary?: string;
              } & {
                [key: string]: unknown;
              });
          repo?: string;
          agent_id?: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_ingest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          files: (
            | string
            | {
                path: string;
                content: string;
              }
          )[];
          repo: string;
          commit?: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "post_api_repos_owner_repo_ingest-graph": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          kinds?: string[];
          commit?: string;
          force?: boolean;
          glob?: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_events_id_payload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_embed: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          text: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_onboard: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          repo: string;
          reonboard?: boolean;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_webhook_slack: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
    };
  };
  post_api_webhook_incident: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
    };
  };
  get_api_repos_owner_repo_webhook: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_webhook_ensure: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_webhook_secret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_tokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_tokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_repos_owner_repo_settings_dark-factory": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "put_api_repos_owner_repo_settings_dark-factory": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          enabled?: boolean;
          /** @enum {string} */
          create_issue?: "never" | "on_gate" | "always";
          auto_merge?: {
            paths?: string[];
            /** @enum {string} */
            min_trust?: "docs" | "tests" | "implementation" | "full";
            require_green_ci?: boolean;
            require_bot_approval?: boolean;
          };
          /** @enum {string} */
          review?: "trust_based" | "always" | "never";
          notify?: ("escalation" | "watched" | "all")[];
          execution?: {
            image?: string;
          };
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_repos_owner_repo_agent-definitions_name": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "put_api_repos_owner_repo_agent-definitions_name": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name: string;
          model?: string | null;
          timeout_minutes?: number | null;
          prompt?: string | null;
          image?: string | null;
          /**
           * @default claude-code
           * @enum {string}
           */
          execution_mode?: "claude-code" | "graph-ingest" | "station";
          /** @default false */
          review_required?: boolean;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "delete_api_repos_owner_repo_agent-definitions_name": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "post_api_repos_owner_repo_agent-definitions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name: string;
          model?: string | null;
          timeout_minutes?: number | null;
          prompt?: string | null;
          image?: string | null;
          /**
           * @default claude-code
           * @enum {string}
           */
          execution_mode?: "claude-code" | "graph-ingest" | "station";
          /** @default false */
          review_required?: boolean;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_usage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_analytics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_agent-stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_impact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          commit?: string;
          base?: string;
          graphCommit?: string | null;
          protocol?: number;
          files?: unknown;
          docs?: unknown;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_impact_base: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_trace_kind: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        kind: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_chunks_kind: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        kind: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_onboarded: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_issues: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_issues: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          title: string;
          body: string;
          labels?: string[];
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_labels: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_branches: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          branch: string;
          base?: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_commit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          branch: string;
          path: string;
          content: string;
          message: string;
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_pulls: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          branch: string;
          title: string;
          body: string;
          base?: string;
          labels?: string[];
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_repos_owner_repo_ci-conclusion": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_tasks_drift: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_repos_owner_repo_tasks_open-like": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_tasks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          description: string;
          taskType: string;
          createdBy?: string;
          contextBundle?: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_trace_adrs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_trace_specs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  "get_api_openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_docs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response (2xx; the response body is not described — see info.description) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_features: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureList"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_features: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureCreated"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_features_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureWithIterations"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  delete_api_repos_owner_repo_features_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_features_id_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeaturePoll"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  get_api_repos_owner_repo_features_id_decomposition: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureDecomposition"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_features_id_iterations: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoundStarted"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_features_id_iterations_n_result: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
        n: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_features_id_finalize: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FinalizeStarted"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  post_api_repos_owner_repo_features_id_split: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner: string;
        repo: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Feature"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      413: components["responses"]["PayloadTooLarge"];
      429: components["responses"]["RateLimited"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
}
