// GENERATED by scripts/gen-builtin-definitions.mjs — do not edit; regenerate with `npm run gen:builtin-definitions`. web-ui is outside the npm workspace and carries no YAML parser, so it needs this copy; generating it is what stops it rotting (it once claimed feature-planning had 2 nodes while the YAML had 9).

import type { AssemblyLineDefinition } from "./assembly-line-definition";
import {
  codeReviewDefinition,
  codeReviewRecheckDefinition,
  codeReviewReplyDefinition,
  commentTriageDefinition,
} from "./builtin-definitions-pr-review";
import {
  gapDetectDefinition,
  ingestDefinition,
  specCoverageBackfillDefinition,
  specCoverageValidateDefinition,
  specDriftDefinition,
} from "./builtin-definitions-internal-events";

export * from "./builtin-definitions-pr-review";
export * from "./builtin-definitions-internal-events";

export const escalationDefinition: AssemblyLineDefinition = {
  name: "escalation",
  description:
    "Tell a human that a task needs them. Started when a task transitions to needs-human-help, keyed by that task so two writers racing cannot file two Issues at the same person.",
  version: 1,
  entry: "file-issue",
  exit: "done",
  nodes: [
    { id: "file-issue", type: "escalation_step" },
    { id: "notify", type: "escalation_step" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "file-issue", to: "notify", on: "success" },
    { from: "file-issue", to: "notify", on: "failed" },
    { from: "notify", to: "done", on: "success" },
    { from: "notify", to: "done", on: "failed" },
  ],
};

export const featurePlanningDefinition: AssemblyLineDefinition = {
  name: "feature-planning",
  description:
    "One interactive planning round: analyze the feature request against the project (with the prior feature timeline in context) and emit a structured GapResult. No commit, no PR — the run declares result.json as a produced artifact (`output.watch`), the subsystem raises it as a `planning.result` event, and the Floor persists it as the round's result.",
  version: 1,
  entry: "analyze",
  exit: "done",
  nodes: [
    { id: "analyze", type: "agent" },
    { id: "author", type: "feature_review" },
    { id: "analyse-specs", type: "agent" },
    { id: "write", type: "agent" },
    { id: "push", type: "agent" },
    { id: "merged", type: "pr_review" },
    { id: "decompose", type: "agent" },
    { id: "issues", type: "issues" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "analyze", to: "author", on: "success" },
    { from: "analyze", to: "author", on: "changes_requested" },
    { from: "author", to: "analyze", on: "changes_requested" },
    { from: "author", to: "analyse-specs", on: "success" },
    { from: "analyse-specs", to: "write", on: "success" },
    { from: "analyse-specs", to: "author", on: "changes_requested" },
    { from: "analyse-specs", to: "done", on: "failed" },
    { from: "write", to: "push", on: "success" },
    {
      from: "write",
      to: "analyse-specs",
      on: "changes_requested",
      iteration_max: 1,
    },
    { from: "write", to: "done", on: "failed" },
    { from: "push", to: "merged", on: "always" },
    { from: "merged", to: "decompose", on: "success" },
    { from: "merged", to: "author", on: "changes_requested" },
    { from: "merged", to: "done", on: "failed" },
    { from: "decompose", to: "issues", on: "success" },
    { from: "decompose", to: "done", on: "changes_requested" },
    { from: "decompose", to: "done", on: "failed" },
    { from: "issues", to: "done", on: "success" },
    {
      from: "issues",
      to: "decompose",
      on: "changes_requested",
      iteration_max: 1,
    },
    { from: "issues", to: "done", on: "failed" },
    { from: "author", to: "done", on: "failed" },
    { from: "analyze", to: "analyze", on: "failed", iteration_max: 1 },
  ],
};

export const gapFillDefinition: AssemblyLineDefinition = {
  name: "gap-fill",
  description:
    "Draft missing context as docs, validate, push. No human review on the auto-merge path.",
  version: 1,
  entry: "draft",
  exit: "done",
  nodes: [
    { id: "draft", type: "agent" },
    { id: "validate", type: "validate" },
    { id: "push", type: "agent" },
    { id: "retrospective", type: "retrospective" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "draft", to: "validate", on: "success" },
    { from: "draft", to: "retrospective", on: "changes_requested" },
    { from: "draft", to: "draft", on: "failed", iteration_max: 1 },
    { from: "validate", to: "push", on: "success" },
    { from: "validate", to: "draft", on: "failed", iteration_max: 1 },
    { from: "push", to: "retrospective", on: "always" },
    { from: "retrospective", to: "done", on: "always" },
  ],
};

export const generalDefinition: AssemblyLineDefinition = {
  name: "general",
  description:
    "Linear flow for general tasks — implement, validate, push, review, retrospective. Used when no more specific assembly line applies.",
  version: 1,
  entry: "implement",
  exit: "done",
  nodes: [
    { id: "implement", type: "agent" },
    { id: "validate", type: "validate" },
    { id: "push", type: "agent" },
    { id: "review", type: "agent" },
    { id: "retrospective", type: "retrospective" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "implement", to: "validate", on: "success" },
    { from: "implement", to: "retrospective", on: "changes_requested" },
    { from: "implement", to: "implement", on: "failed", iteration_max: 1 },
    { from: "validate", to: "push", on: "success" },
    { from: "validate", to: "implement", on: "failed", iteration_max: 1 },
    { from: "push", to: "review", on: "always" },
    { from: "review", to: "retrospective", on: "success" },
    { from: "review", to: "retrospective", on: "changes_requested" },
    { from: "review", to: "retrospective", on: "failed" },
    { from: "retrospective", to: "done", on: "always" },
  ],
};

export const implementationDefinition: AssemblyLineDefinition = {
  name: "implementation",
  description:
    "Implement a spec, validate, push, review. On changes_requested, address feedback up to 2 iterations.",
  version: 1,
  entry: "implement",
  exit: "done",
  nodes: [
    { id: "implement", type: "agent" },
    { id: "validate", type: "validate" },
    { id: "push", type: "agent" },
    { id: "review", type: "agent" },
    { id: "address", type: "agent" },
    { id: "retrospective", type: "retrospective" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "implement", to: "validate", on: "success" },
    { from: "implement", to: "implement", on: "failed", iteration_max: 1 },
    { from: "implement", to: "retrospective", on: "changes_requested" },
    { from: "validate", to: "push", on: "success" },
    { from: "validate", to: "implement", on: "failed", iteration_max: 1 },
    { from: "push", to: "review", on: "always" },
    { from: "review", to: "retrospective", on: "success" },
    {
      from: "review",
      to: "address",
      on: "changes_requested",
      iteration_max: 2,
    },
    { from: "address", to: "validate", on: "always", iteration_max: 2 },
    { from: "review", to: "retrospective", on: "failed" },
    { from: "retrospective", to: "done", on: "always" },
  ],
};

export const implementationLoopDefinition: AssemblyLineDefinition = {
  name: "implementation-loop",
  description:
    "Work one backlog ticket top-down — acceptance tests first, then one red-green-refactor round per visit — behind a draft PR, and park until it is green with no unresolved review threads. Never merges.",
  version: 1,
  entry: "dod",
  exit: "done",
  nodes: [
    { id: "dod", type: "agent" },
    { id: "open-pr", type: "agent" },
    { id: "tdd-round", type: "agent" },
    { id: "ready-for-review", type: "agent" },
    { id: "await-pr", type: "pr_review" },
    { id: "fix-ci", type: "agent" },
    { id: "retrospective", type: "retrospective" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "dod", to: "open-pr", on: "success" },
    { from: "dod", to: "dod", on: "failed", iteration_max: 1 },
    { from: "dod", to: "retrospective", on: "changes_requested" },
    { from: "open-pr", to: "tdd-round", on: "success" },
    { from: "open-pr", to: "retrospective", on: "failed" },
    { from: "open-pr", to: "retrospective", on: "changes_requested" },
    {
      from: "tdd-round",
      to: "tdd-round",
      on: "changes_requested",
      iteration_max: 12,
    },
    { from: "tdd-round", to: "ready-for-review", on: "success" },
    { from: "tdd-round", to: "retrospective", on: "failed" },
    { from: "ready-for-review", to: "await-pr", on: "success" },
    {
      from: "ready-for-review",
      to: "ready-for-review",
      on: "failed",
      iteration_max: 1,
    },
    { from: "ready-for-review", to: "retrospective", on: "changes_requested" },
    { from: "await-pr", to: "retrospective", on: "success" },
    {
      from: "await-pr",
      to: "fix-ci",
      on: "changes_requested",
      iteration_max: 3,
    },
    { from: "await-pr", to: "retrospective", on: "failed" },
    { from: "fix-ci", to: "await-pr", on: "success" },
    { from: "fix-ci", to: "retrospective", on: "failed" },
    { from: "fix-ci", to: "retrospective", on: "changes_requested" },
    { from: "retrospective", to: "done", on: "always" },
  ],
};

export const mergeDefinition: AssemblyLineDefinition = {
  name: "merge",
  description:
    "Everything that must happen once a task's PR merges. It was one function behind five swallowing try/catch blocks and three unguarded awaits, so a throw in the middle skipped every step after it — including the one that un-parks a feature's planning line, which a trust-ladder blip could therefore strand forever.",
  version: 1,
  entry: "settle",
  exit: "done",
  nodes: [
    { id: "settle", type: "merge_step" },
    { id: "spec-status", type: "merge_step" },
    { id: "close-issue", type: "merge_step" },
    { id: "outcome-stats", type: "merge_step" },
    { id: "curate", type: "merge_step" },
    { id: "memory-feedback", type: "merge_step" },
    { id: "trust", type: "merge_step" },
    { id: "spec-tasks", type: "merge_step" },
    { id: "resume-planning", type: "merge_step" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "settle", to: "spec-status", on: "success" },
    { from: "settle", to: "done", on: "failed" },
    { from: "spec-status", to: "close-issue", on: "success" },
    { from: "spec-status", to: "close-issue", on: "failed" },
    { from: "close-issue", to: "outcome-stats", on: "success" },
    { from: "close-issue", to: "outcome-stats", on: "failed" },
    { from: "outcome-stats", to: "curate", on: "success" },
    { from: "outcome-stats", to: "curate", on: "failed" },
    { from: "curate", to: "memory-feedback", on: "success" },
    { from: "curate", to: "memory-feedback", on: "failed" },
    { from: "memory-feedback", to: "trust", on: "success" },
    { from: "memory-feedback", to: "trust", on: "failed" },
    { from: "trust", to: "spec-tasks", on: "success" },
    { from: "trust", to: "spec-tasks", on: "failed" },
    { from: "spec-tasks", to: "resume-planning", on: "success" },
    { from: "spec-tasks", to: "resume-planning", on: "failed" },
    { from: "resume-planning", to: "done", on: "success" },
    { from: "resume-planning", to: "done", on: "failed" },
  ],
};

export const builtinDefinitions: AssemblyLineDefinition[] = [
  codeReviewDefinition,
  codeReviewRecheckDefinition,
  codeReviewReplyDefinition,
  commentTriageDefinition,
  gapDetectDefinition,
  ingestDefinition,
  specCoverageBackfillDefinition,
  specCoverageValidateDefinition,
  specDriftDefinition,
  escalationDefinition,
  featurePlanningDefinition,
  gapFillDefinition,
  generalDefinition,
  implementationDefinition,
  implementationLoopDefinition,
  mergeDefinition,
];
