// GENERATED by scripts/gen-builtin-definitions.mjs — do not edit; regenerate with `npm run gen:builtin-definitions`. web-ui is outside the npm workspace and carries no YAML parser, so it needs this copy; generating it is what stops it rotting (it once claimed feature-planning had 2 nodes while the YAML had 9). The PR-review family.

import type { AssemblyLineDefinition } from "./assembly-line-definition";

export const codeReviewDefinition: AssemblyLineDefinition = {
  name: "code-review",
  description:
    "Review a PR — assess the diff and emit structured findings; the Floor posts them as suggestion-only Conventional Comments. Fixes are human-gated via replies.",
  version: 1,
  entry: "review",
  exit: "done",
  nodes: [
    { id: "review", type: "agent" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "review", to: "done", on: "success" },
    { from: "review", to: "done", on: "changes_requested" },
    { from: "review", to: "review", on: "failed", iteration_max: 1 },
  ],
};

export const codeReviewRecheckDefinition: AssemblyLineDefinition = {
  name: "code-review-recheck",
  description:
    "Fast re-check after a new push — re-assess the updated diff and emit a REVIEW_RESULT verdict so the PR's formal APPROVE / REQUEST_CHANGES tracks the fix. Cheap model, short timeout. Started per push once the deep review has run.",
  version: 1,
  entry: "recheck",
  exit: "done",
  nodes: [
    { id: "recheck", type: "agent" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "recheck", to: "done", on: "success" },
    { from: "recheck", to: "done", on: "changes_requested" },
    { from: "recheck", to: "recheck", on: "failed", iteration_max: 1 },
  ],
};

export const codeReviewReplyDefinition: AssemblyLineDefinition = {
  name: "code-review-reply",
  description:
    "Act on a human reply to a review comment — answer in-thread, or (on approval) commit the fix. Started by the comment-triage router or a submitted review.",
  version: 1,
  entry: "reply",
  exit: "done",
  nodes: [
    { id: "reply", type: "agent" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "reply", to: "done", on: "success" },
    { from: "reply", to: "done", on: "changes_requested" },
    { from: "reply", to: "done", on: "failed" },
  ],
};

export const commentTriageDefinition: AssemblyLineDefinition = {
  name: "comment-triage",
  description:
    "Classify a human PR comment (Haiku station) and route it — the Floor reads the triage action and starts the review / address / answer follow-up (or nothing, on ignore).",
  version: 1,
  entry: "triage",
  exit: "done",
  nodes: [
    { id: "triage", type: "comment-triage" },
    { id: "done", type: "retrospective" },
  ],
  edges: [
    { from: "triage", to: "done", on: "success" },
    { from: "triage", to: "done", on: "failed" },
  ],
};
